### ISSUE TITLE
2a979f5 breaks package-installed passnger

### ISSUE THREAD

**Issue by yule** [capistrano/passenger#18]
When passenger is installed form a package (eg apt-get), passenger is not available in the path so can't get the version number. You can specify this in env variables, however in this instance, running passenger -v, still wouldn't return anything.

Perhaps the option to specify which version of passenger is being used, rather than trying to detect. (or a command that lets you specify the version) eg `dpkg -l | grep passenger` or similar.

**Comment by betesh** [comment]
Can you submit a PR that addresses this?

**Comment by yule** [comment]
https://github.com/capistrano/passenger/pull/19

**Comment by betesh** [comment]
@yule Am I correct that 33b5c676245601e6f580c4b50acbfd2f3b124d98 addresses this sufficiently?

If yes, please close this and #19

**Comment by yule** [comment]
@betesh 33b5c67 would be a work around for  versions under 4.0.33, and would solve my initial issues. 
However those above this version, where you can't run `passenger -v` from command line (perhaps needing sudo?), this would still fail. I'm not sure whether this is a feasible scenario as I've not yet played with passenger 5.

**Comment by betesh** [comment]
If you need sudo, that's going to require additional configuration anyway.  If you don't run into problems early in deployment, you will later in deployment, so that's really just a matter of giving the user the most useful error message, as early as possible.  Not within the scope of this ticket but feel free to submit a new PR.

Since your issue is resolved, I'm closing this and #19.
