### ISSUE TITLE
cap deploy fails due to 2 passenger instances running

### ISSUE THREAD

**Issue by IanVaughan** [capistrano/passenger#34]
Not sure how this can be solved, but here is the error output from cap deploy :

```
DEBUG [8342f1fc]        It appears that multiple Phusion Passenger instances are running. Please select
DEBUG [8342f1fc]        a specific one by passing:
DEBUG [8342f1fc]
DEBUG [8342f1fc]          --instance <NAME>
DEBUG [8342f1fc]
DEBUG [8342f1fc]        The following Phusion Passenger instances are running:
DEBUG [8342f1fc]
DEBUG [8342f1fc]        Name                       Description
DEBUG [8342f1fc]        ------------------------------------------------------------------
DEBUG [8342f1fc]        Hti7gcXg                   nginx/1.8.0 Phusion_Passenger/5.0.14
DEBUG [8342f1fc]        WnX8S9fI                   Apache/2.4.7 (Ubuntu) Phusion_Passenger/5.0.14
(Backtrace restricted to imported tasks)
cap aborted!
```

So on the server, I see the two instances :

```
$ passenger-status
It appears that multiple Phusion Passenger instances are running. Please
select a specific one by running:

  passenger-status <NAME>

The following instances are running:

Name                       Description
------------------------------------------------------------------
Hti7gcXg                   nginx/1.8.0 Phusion_Passenger/5.0.14
WnX8S9fI                   Apache/2.4.7 (Ubuntu) Phusion_Passenger/5.0.14
```

And can manually restart :

```
$ passenger-config restart-app --instance Hti7gcXg .
Restarting /srv/www/myapp/current/public
```

But of course the instance name could change, so cannot be hard coded into the cap deploy scripts.

**Comment by betesh** [comment]
My suggestion is to add a capistrano task to get the instance:

```
task :get_passenger_instance_name do
  set :passenger_instance_name, capture(:"passenger-status").scan(/^(\S*)\s*nginx*$/)[1]
end

set :passenger_restart_command, 
  ->{ "passenger-config restart-app --instance #{fetch(:passenger_instance_name)}" }
```

I don't guarantee the regex is perfect but it should point you in the right direction.

Keep in mind, however, that if you're restarting multiple instances, this won't work because the instance ID will be different on each instance.  In that case, you would need to put the regex logic into the bash command itself.  Something like this:

```
set :passenger_restart_command, 
  ->{ "passenger-config restart-app --instance \`passenger-status | sed -r \"/(.*)nginx/\"\`" }
```

But then you'll need to manually add the command map prefix to the passenger status command.  This could get pretty messy.

**Comment by betesh** [comment]
@IanVaughan Let me know if you came up with a solution.  If you want to add some info to the README about how to handle multiple instances, please submit a PR.

**Comment by IanVaughan** [comment]
Many thanks for your help, I played with the regex but I didn't have much luck.
So instead we just thought it best to only have one passenger instance running, and moved everything over to nginx.
Sorry that I was not able to help solve this as I'm sure it would be valuable to others.
(Not sure if you want to close it or not?)

**Comment by fuminori-ido** [comment]
I faced the same situation (both Apache & Nginx running and I would like to apply cap + passenger for my rails app to Nginx).  @betesh shed light  to my case (many thanks!).  Let me correct wrong regex written above and add some tasks what I needed as follows:

``` ruby
task :get_passenger_instance_name do
  on roles(:app) do
    set :passenger_instance_name, capture(:"/FULL/PATH/TO/passenger-status || true").scan(/^(\S+)\s+nginx.*$/)[0][0]
  end
end

set :passenger_restart_command,
  ->{ "passenger-config restart-app --instance #{fetch(:passenger_instance_name)}" }

before :deploy, :get_passenger_instance_name
```

1) According to String#scan spec, I needed to write as above.
2) "on roles do ... end" block is needed.  Otherwise, "undefined method `capture`..." happened in my case (cap 3.3.5)
3) I needed to specify full path to passenger-status command (I don't know why).
4) Passenger-status should exit with error-status (!=0) because of multiple instances so that ignorance is needed under cap execution.  Adding "|| false" to the command was needed, in my case.
5) This task should be run before deploy so that I added the dependency on both.

**Comment by betesh** [comment]
1) Thanks for sharing the correct regex!
2) `capture` is only defined in the context of a command running on a server.  Outside the `on`-block, your in a native rake context (ok, that's oversimplifying, but basically, you can't run a shell command on a remote server without saying "run the following command **on** server X")
3) capistrano-passenger only adds the necessary prefixes to the commands `passenger` and `passenger-config`.  Look at https://github.com/capistrano/passenger/blob/master/lib/capistrano/tasks/passenger.cap and feel free to add `passenger-status` everywhere that you see the array `[:passenger, :'passenger-config']`.  If you submit a PR that does that, I'll merge it.  After that, you **might** have to change `before :deploy, :get_passenger_instance_name` to `after :deploy, :get_passenger_instance_name` to make sure we've already added the prefixes, but whether you need to make that change or not may depend on what order gems are required in your Capfile.
4) Instead of `|| false` or `|| true`, you can just pass `raise_on_non_zero_exit: false` to the `capture` method.
5) Not sure what you mean by `so that I added the dependency on both.`.  I don't see why `before :'passenger:restart, :get_passenger_instance_name` wouldn't work

**Comment by betesh** [comment]
Also, @fuminori-ido, I assume the instance ID will be different on each server, so if you're running more than 1 app server, this will get more complex.

**Comment by rubyistdotjs** [comment]
I do not use this gem, but I came here because I had the same issue.
Our app use Passenger Apache and I need to setup Passenger Standalone for ActionCable (the Apache version doesn't support it).

The solution above didn't work, it throw me an error : 

``` shell
SSHKit::Runner::ExecuteError: Exception while executing as domain@domain.com: passenger-status exit status: 1
passenger-status stdout: It appears that multiple Phusion Passenger instances are running. Please
select a specific one by running ...
```

So I'll paste my solution here in case someone run into the same problem :

``` ruby
namespace :deploy do

  desc 'Restart ActionCable'
  task :restart_action_cable do
    on roles(:app), in: :sequence, wait: 5 do
      instances = JSON.parse(capture(:'passenger-config', 'list-instances', '--json'))
      instance_name = instances.find { |i| i['integration_mode'] == 'standalone' }&.dig('name')

      if instance_name.nil?
        # the server isn't running, put your code to start it here or throw an error
      else
        execute(:'passenger-config', 'restart-app', current_path, '--instance', instance_name)
      end
    end
  end

  after :publishing, :restart_action_cable

end
```

_You'll need to add `require 'json'` to your Capfile also the code above require at least Ruby 2.3, otherwise replace `&.dig('name')` with code to test if something was found or just `['name']` but it will throw an error if the instance isn't running._

**Comment by ablagoev** [comment]
Alternatively when using Passenger Standalone you can set the [passenger_instance_registry_dir](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_instance_registry_dir) for each instance you are running. In our case, we set it directly in the Passengerfile.json

You will need to alter your deploy.rb file as follows:

`set :passenger_environment_variables, { 'PASSENGER_INSTANCE_REGISTRY_DIR' => 'YOUR_NEW_DIRECTORY' }
`

This is needed, so that all passenger related commands (passenger-config for example) know to work with the custom directory.

**Comment by lumentut** [comment]
@fuminori-ido, I use your code with a little modification so that the instance name can be capture automatically depends on which server you use whether 'nginx' or 'apache'.

First find the instance info by using `grep -i 'apache'` (if the app use passenger-apache) then capture the instance name using `cut -c 1-8`. Since the length of instance name is 8 characters. So, everything can be done automatically.

```ruby
task :get_passenger_instance_name do
  on roles(:app) do
    set :passenger_instance_name, capture("passenger-status | grep -i 'apache' | cut -c 1-8")
  end
end

set :passenger_restart_command,
  ->{ "passenger-config restart-app --instance #{fetch(:passenger_instance_name)}" }

before :deploy, :get_passenger_instance_name
```
I hope it can help someone who still needs the solution
