### ISSUE TITLE
passenger relative url and port

### ISSUE THREAD

**Issue by u007** [capistrano/passenger#38]
hi,

i'am running passenger via standalone.
ive custom port 3065 and also some rails instance have relative url.

how do i pass this information to capistrano-passenger?

thank you

**Comment by betesh** [comment]
This doesn't sound like a bug.  If there's something unclear in the capistrano-passenger README, please be specific about what's unclear and I will gladly re-open this.

Otherwise, if you're just looking for general guidance, I suggest asking on StackOverflow.com and sharing whatever solutions you've attempted so far.
