### ISSUE TITLE
passenger restart problems

### ISSUE THREAD

**Issue by manzhikov** [capistrano/passenger#8]
I installed passenger from rvm. rvm_type is system
When I call it from deploy user command exists.

From cap script I getting this error:

```
DEBUG [b141b962] Command: passenger-config restart-app
DEBUG [b141b962]    bash: passenger-config: command not found
```

When I tried to set path to passenger config, I got this:

```
DEBUG [73ebbfcd] Command: /usr/local/rvm/gems/ruby-2.2.1/bin/passenger-config restart-app
DEBUG [73ebbfcd]    /usr/bin/env: ruby_executable_hooks
DEBUG [73ebbfcd]    : No such file or directory
```

rvm_hook output:

```
DEBUG [f80d9333] Running /usr/local/rvm/bin/rvm version as 
DEBUG [f80d9333] Command: /usr/local/rvm/bin/rvm version
DEBUG [f80d9333]    rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
DEBUG [f80d9333] Finished in 1.724 seconds with exit status 0 (successful).
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
DEBUG [4fc78198] Running /usr/local/rvm/bin/rvm current as 
DEBUG [4fc78198] Command: /usr/local/rvm/bin/rvm current
DEBUG [4fc78198]    ruby-2.2.1
DEBUG [4fc78198] Finished in 0.679 seconds with exit status 0 (successful).
ruby-2.2.1
DEBUG [f83a8bea] Running /usr/local/rvm/bin/rvm default do ruby --version as 
DEBUG [f83a8bea] Command: /usr/local/rvm/bin/rvm default do ruby --version
DEBUG [f83a8bea]    ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
DEBUG [f83a8bea] Finished in 1.024 seconds with exit status 0 (successful).
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```

**Comment by clemensg** [comment]
Same here.

**Comment by betesh** [comment]
I just pushed to master a commit that will probably fix this by making sure that the call to `passenger-config` uses the command map.  Please try this and I expect the deployment script to find the executable correctly and be able to execute it.  (If you try this, please post the output here so we can confirm that it _is_ finding the executable.)

However, I must warn you that, as we've been discussing in #2, `passenger-config` will probably exit with some error along the lines of "You are not authorized to query the status for this Phusion Passenger instance" because you can't restart without root privileges.  There are some suggestions in #2 for how to deal with that.  I am waiting to see how phusion/passenger#1392 is addressed before adding any further instructions to the README about how to do this.

**Comment by manzhikov** [comment]
@betesh yes, it solved the problem.
Other problem now to run passenger-config with sudo and no password, like at the link that you sent.

Thanks.

**Comment by themilkman** [comment]
@betesh Thanks for the fix! It solved my issue where passenger would ask which instance to restart, which 'froze' my deployment, like that

```
INFO [b4c76c25] Running /usr/bin/env passenger-config restart-app /path/to/myapplication --ignore-app-not-running as deployer@myhost
DEBUG [b4c76c25] Command: passenger-config restart-app
DEBUG [b4c76c25]     Please select the application to restart.
DEBUG [b4c76c25]     [1mTip: re-run this command with --help to learn how to automate it.[37m[40m
DEBUG [b4c76c25]     [1m[90mIf the menu doesn't display correctly, press '!'[0m[37m[40m
DEBUG [b4c76c25]     [?25l ‣   /path/to/myapplication/current#default
DEBUG [b4c76c25]          Cancel
```
